In [1]:
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import statsmodels.api as sm
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import make_blobs
from sklearn.naive_bayes import GaussianNB

In [2]:
data = pd.read_csv("House.csv")

In [3]:
data.isnull()

Type  Bedroom  Bathroom  Sold?
0  False    False     False  False
1  False    False     False  False
2  False    False     False  False
3  False    False     False  False
4  False    False     False  False
5  False    False     False  False
6  False    False     False  False
7  False    False     False  False
8  False    False     False  False
9  False    False     False  False

In [4]:
data.isnull().any()

Type        False
Bedroom     False
Bathroom    False
Sold?       False
dtype: bool

In [5]:
data.head(11)

Type  Bedroom  Bathroom Sold?
0  TownH        2         1   Yes
1  TownH        2         1    No
2  TownH        2         1   Yes
3  Ranch        3         2    No
4  Ranch        3         2   Yes
5  Ranch        3         2    No
6  Ranch        3         2   Yes
7  Ranch        3         2    No
8  TownH        2         1    No
9  TownH        2         1   Yes

In [6]:
le = LabelEncoder()
data['Type'] = le.fit_transform(data['Type'])
data['Sold?'] = le.fit_transform(data['Sold?'])

In [7]:
data.head(10)

Type  Bedroom  Bathroom  Sold?
0     1        2         1      1
1     1        2         1      0
2     1        2         1      1
3     0        3         2      0
4     0        3         2      1
5     0        3         2      0
6     0        3         2      1
7     0        3         2      0
8     1        2         1      0
9     1        2         1      1

In [8]:
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [9]:
model = GaussianNB()
model.fit(x, y)

GaussianNB()

In [10]:
pred = model.predict(x)
accur = accuracy_score(y, pred)

In [11]:
accur

0.6

In [12]:
data.head()

Type  Bedroom  Bathroom  Sold?
0     1        2         1      1
1     1        2         1      0
2     1        2         1      1
3     0        3         2      0
4     0        3         2      1

In [13]:
a = [[1,2,1]]

In [14]:
model.predict(a)

array([1])

In [15]:
#Linear Regression Part:

In [16]:
regression = LinearRegression()
regression.fit(x, y)

LinearRegression()

In [17]:
regression.intercept_

0.7333333333333332

In [18]:
regression.coef_

array([ 0.06666667, -0.06666667, -0.06666667])

In [19]:
prediction = regression.predict(x)

In [20]:
prediction

array([0.6, 0.6, 0.6, 0.4, 0.4, 0.4, 0.4, 0.4, 0.6, 0.6])

In [21]:
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
import numpy as np
import math
from sklearn.metrics import accuracy_score

In [22]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y, prediction))
print('Mean Squared Error:', metrics.mean_squared_error(y, prediction))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y, prediction)))

Mean Absolute Error: 0.4800000000000001
Mean Squared Error: 0.24
Root Mean Squared Error: 0.4898979485566356


In [23]:
x = data[['Type', 'Bedroom', 'Bathroom']]
y = data['Sold?']
x = sm.add_constant(x)
model = sm.OLS(y, x).fit()
pr = model.predict(x)
pm = model.summary()
print(pm)

                            OLS Regression Results                            
Dep. Variable:                  Sold?   R-squared:                       0.040
Model:                            OLS   Adj. R-squared:                 -0.080
Method:                 Least Squares   F-statistic:                    0.3333
Date:                Wed, 18 Nov 2020   Prob (F-statistic):              0.580
Time:                        15:15:49   Log-Likelihood:                -7.0538
No. Observations:                  10   AIC:                             18.11
Df Residuals:                       8   BIC:                             18.71
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.1294      0.078      1.668      0.1

C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "
